/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-dim": "#4f46e5",
        "secondary": "#e4e2e1",
        "on-tertiary": "#655400",
        "on-error-container": "#ffa8a3",
        "primary-fixed-dim": "#6366f1",
        "outline-variant": "#484847",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#4338ca",
        "on-surface": "#ffffff",
        "on-background": "#ffffff",
        "on-secondary-container": "#d2d0cf",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#d6d4d3",
        "primary-container": "#818cf8",
        "secondary-container": "#474747",
        "on-primary-fixed": "#000000",
        "surface-container-high": "#201f1f",
        "primary": "#6366f1",
        "surface-container": "#1a1919",
        "on-tertiary-fixed": "#453900",
        "surface-bright": "#2c2c2c",
        "outline": "#777575",
        "surface-container-highest": "#262626",
        "tertiary": "#ffe792",
        "surface-container-lowest": "#000000",
        "surface": "#0e0e0e",
        "inverse-surface": "#fcf9f8",
        "tertiary-dim": "#efc900",
        "surface-variant": "#262626",
        "tertiary-fixed-dim": "#efc900",
        "on-tertiary-container": "#5b4b00",
        "secondary-fixed": "#e4e2e1",
        "background": "#0e0e0e",
        "on-error": "#490006",
        "on-surface-variant": "#adaaaa",
        "tertiary-fixed": "#ffd709",
        "on-secondary-fixed": "#3f3f3f",
        "on-secondary-fixed-variant": "#5c5b5b",
        "on-secondary": "#525151",
        "tertiary-container": "#ffd709",
        "secondary-dim": "#d6d4d3",
        "error-dim": "#d7383b",
        "surface-container-low": "#131313",
        "surface-dim": "#0e0e0e",
        "on-tertiary-fixed-variant": "#665500",
        "error-container": "#9f0519",
        "inverse-on-surface": "#565555",
        "on-primary-fixed-variant": "#312e81",
        "surface-tint": "#6366f1",
        "primary-fixed": "#818cf8",
        "error": "#ff716c",

        // Adding kw- mapping so un-migrated components don't instantly break, though I will try to migrate them
        "kw-surface": "#0e0e0e",
        "kw-surface-container-low": "#131313",
        "kw-surface-container": "#1a1919",
        "kw-surface-container-high": "#201f1f",
        "kw-surface-container-highest": "#262626",
        "kw-surface-variant": "#262626",
        "kw-primary": "#6366f1",
        "kw-primary-container": "#818cf8",
        "kw-on-primary-fixed": "#000000",
        "kw-secondary": "#e4e2e1",
        "kw-secondary-container": "#474747",
        "kw-tertiary": "#ffe792",
        "kw-tertiary-container": "#ffd709",
        "kw-outline-variant": "#484847"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
        "sans": ["Manrope", "sans-serif"],
        "mono": ["Space Grotesk", "monospace"],
      },
      boxShadow: {
        "silk-extruded": "8px 8px 16px #080c16, -4px -4px 12px rgba(255, 255, 255, 0.02)",
        "silk-pressed": "inset 4px 4px 8px #080c16, inset -2px -2px 6px rgba(255, 255, 255, 0.05)",
        "silk-soft": "0 10px 25px -5px rgba(99, 102, 241, 0.2), 0 8px 10px -6px rgba(99, 102, 241, 0.2)"
      }
    },
  },
  plugins: [],
}
